### ISSUE TITLE
manage.py syncd: error: unrecognised arguments --all

### ISSUE THREAD

**Issue by hybrid1969** [evewspace/eve-wspace#246]
trying a fresh build of W-spsace as I havent used it for a year and using RTD for install instructions and stuck at -
./manage.py syncdb --all --noinput

Any guide to what i need to change to complete the install as I'm not a python guy and not sure where to start. should I adjust the settings.py as I noticed the database entry is wrong for my build?

**Comment by literallybased** [comment]
Just use `./manage.py syncdb --noinput`

**Comment by hybrid1969** [comment]
Sorry I forgot to say I had already tried that and got this and I honestly dont even know where to start looking. Im sure ive done something dumb because when i setup the previous version i was pretty simple -

System check identified some issues:
WARNINGS:
API.APIAccessRequirement.corps_required: (fields.W340) null has no effect on ManyToManyField.
API.APIAccessRequirement.groups_required: (fields.W340) null has no effect on ManyToManyField.
Slack.SlackChannel.group: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
core.LocationWormholeClass.location: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
core.StarbaseResource.towerType: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(_args, *_options)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", *_options)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 120, in call_command
    return command.execute(_args, *_defaults)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(_args, **options)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in **init**
    self.loader = MigrationLoader(self.connection)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in **init**
    self.build_graph()
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 164, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 21, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

**Comment by quinnjr** [comment]
> django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

Make sure you have the database settings correct in your local_settings.py, then try again.

**Comment by hybrid1969** [comment]
checked everything, even started with a completely fresh server instance.

everything is fine until that point, i can even access the MySql server with the same password thats in the local_settings.py

Any other clues as to the cause

**Comment by quinnjr** [comment]
A clean install of evewspace doesn't set line 25 in local_setting.py to whatever database engine you're using.

From the error message you posted above, you haven't set an engine value, ie: django.db.backends.**mysql**, django.db.backends.**postgresql**, etc.

**Comment by hybrid1969** [comment]
ok now i feel dumb....I didn't even notice that line was wrong for some reason.. 

That fixed it, thanks guys.
