### ISSUE TITLE
API new key: Column 'access_mask' cannot be null

### ISSUE THREAD

**Issue by ndtx** [evewspace/eve-wspace#248]
```
Internal Server Error: /api/key/new/
Traceback (most recent call last):
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/maptool/eve-wspace/evewspace/API/views.py", line 78, in edit_keys
    api_key.validate()
  File "/home/maptool/eve-wspace/evewspace/API/models.py", line 143, in validate
    self.save()
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/models/base.py", line 761, in save_base
    self._save_parents(cls, using, update_fields)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/models/base.py", line 786, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1048, "Column 'access_mask' cannot be null")
[10/Apr/2016 21:19:40] "POST /api/key/new/ HTTP/1.1" 500 14819
```

As workaround I changed the column to be nullable.

Edit: The original sources are from github Unsettled/eve-wspace. If there is a lack of sync, please ignore it.

**Comment by proycon** [comment]
I experienced this too in my previous upgrade, solved it in the same way..

**Comment by Maarten28** [comment]
Now the field will allow null values.
